#23: Updated dependecies
exasol/hive-virtual-schema pull request #24
Opened 2021-11-11 12:38 UTC by umitbuyuksahin

Fixes #23

2021-11-11 19:10 UTC, morazow requested changes

2021-11-11 19:10 UTC, morazow commented on .settings/org.eclipse.core.resources.prefs
> +eclipse.preferences.version=1
I think this was generated by eclipse and not project-keeper, could you please remove it?

2021-11-23 08:12 UTC, jakobbraun approved these changes

2021-11-23 08:18 UTC, morazow approved these changes

2021-11-23 08:19 UTC, merged